<?php
/**
 * Test class for ParticipantController.
 * Generated by PHPUnit on 2012-06-29 at 13:09:10.
 * Test passed on 20121214
 */
class FriendControllerTest extends UnitTestCase
{
	public $fixturesOff=array(
			'user' => 'User',
			'person' => 'Person',
	        'friend' => 'Friend',
	);

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	*/
	protected function setUp()
	{
		$_SERVER=array(
				'SERVER_NAME'=>'testing.local', // the other fields should follow
				'SCRIPT_FILENAME'=> realpath("../../index.php"), // the other fields should follow
				'SCRIPT_NAME'=>'index.php', // the other fields should follow
				'REQUEST_URI' => 'participant/register',
				'PHP_SELF'=>'', // the other fields should follow
		);
		//$wpdb->dbh = Yii::app()->db;
		parent::setup();
	}


	/**
	 * to test that new request form appears properly
	 */
	public function testactionNew()
	{
	    $mockSession = $this->getMock('CHttpSession', array('regenerateID'));
	    Yii::app()->setComponent('session', $mockSession);
	    
	    $this->getFixtureManager()->load(array(
	            'user'=>'User',
	    ));
	    
	    $_SERVER['REQUEST_METHOD'] = 'POST';
	    $_POST['LoginForm']['username'] = 'friskU6P6@testing.com';
	    $_POST['LoginForm']['password'] = 'frisk33@BAD';
	    Yii::app()->runController('site/login');
	    
	    global $redirect_url,$redirect_status;

	    	    
		Yii::app()->runController('friends/new');
		
		$this->assertXpathExists('//form//input[@name="Friend[person2email]"]');
		//$this->assertOutputContains('Subscription Status: Inactive');
	}

}
